(()=>{
const questions={
week1:['What kind of leader do I want people to experience when they work with me?','Which leadership situations currently cause me to hesitate or second-guess myself?','What would I do differently if I trusted my leadership judgement more?'],
week2:['When I feel evaluated or challenged at work, what changes in the way I speak, listen or behave?','Which habit most reduces my leadership presence?','If I focused less on how I was being judged and more on contributing effectively, what might I do differently?'],
week3:['When I anticipate disagreement or confrontation, what do I normally do?','What conversation, boundary or disagreement am I currently avoiding because I am concerned about the other person’s reaction?','What is the cost if I continue avoiding it?']};
const dayTitles={week1:['Self-esteem: worth beyond performance','Confidence: build evidence','Assertiveness: notice hesitation','Communication: make leadership visible','Presentation: speak with self-trust'],week2:['Self-esteem: take up appropriate space','Confidence: pause is authority','Communication: lead with the point','Presentation: deliver a 60–90 second update','Assertiveness: hold your position calmly'],week3:['Assertiveness: name the real issue','Communication: listen without surrendering','Confidence: make a clear request','Self-esteem: disagree without shrinking','Presentation: answer a challenging question clearly']};
let data=null,section='overview',week='week1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const state=()=>data?.elrpState||{};const habits=()=>data?.elrpDailyHabits||{};
function countReflections(){return Object.values(state().reflections||{}).filter(v=>String(v).trim()).length}
function countNotes(){let n=0;Object.values(habits()).forEach(w=>Object.values(w||{}).forEach(d=>{if(d?.note?.trim())n++}));return n}
function stats(){const completed=(state().completed||[]).length;document.getElementById('adminStats').innerHTML=`<div class="wrv-stat"><span>Reflections captured</span><strong>${countReflections()}/9</strong></div><div class="wrv-stat"><span>Daily notes</span><strong>${countNotes()}/15</strong></div><div class="wrv-stat"><span>Weeks completed</span><strong>${completed}/6</strong></div><div class="wrv-stat"><span>Last client sync</span><strong style="font-size:17px">${data?.updatedAt?new Date(data.updatedAt).toLocaleString():'No data yet'}</strong></div>`}
function answer(q,a){const has=String(a||'').trim();return `<div class="wrv-answer ${has?'':'empty'}"><div class="q">${esc(q)}</div><div class="a">${has?esc(a):'No response yet.'}</div></div>`}
function overview(){const s=state();const priorities=['Self-esteem','Confidence','Assertiveness','Communication','Presentation skills'];const scores=s.priorityScores||s.priorityFocus||{};document.getElementById('adminView').innerHTML=`<h2>Coaching overview</h2><p class="wrv-admin-meta">Use the sections on the left to review detailed client entries. This dashboard is read-only.</p><div class="wrv-answer-grid">${priorities.map(p=>answer(p,typeof scores[p]==='number'?`${scores[p]}/10`:scores[p]||'')).join('')}</div>`}
function responses(){const s=state();document.getElementById('adminView').innerHTML=`<h2>Client reflections</h2><div class="wrv-week-tabs">${Object.keys(questions).map(k=>`<button class="${k===week?'active':''}" data-week="${k}">${k.replace('week','Week ')}</button>`).join('')}</div><div class="wrv-answer-grid">${questions[week].map((q,i)=>answer(q,s.reflections?.[`${week}-${i}`])).join('')}</div>`;document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{week=b.dataset.week;responses()})}
function daily(){const h=habits();document.getElementById('adminView').innerHTML=`<h2>Daily leadership practice notes</h2><div class="wrv-week-tabs">${Object.keys(dayTitles).map(k=>`<button class="${k===week?'active':''}" data-week="${k}">${k.replace('week','Week ')}</button>`).join('')}</div><div class="wrv-note-list">${dayTitles[week].map((t,i)=>{const entry=h?.[week]?.[i]||{};return `<div class="wrv-note"><strong>Day ${i+1} · ${esc(t)} ${entry.done?'✓':''}</strong><p>${entry.note?.trim()?esc(entry.note):'<span style="color:#9aa5aa;font-style:italic">No note yet.</span>'}</p></div>`}).join('')}</div>`;document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{week=b.dataset.week;daily()})}
function assessment(){const s=state(),a=s.assessmentReflection||{};const dims=['Confidence in leadership capability','Trust in judgement','Leadership presence in meetings','Remaining composed when challenged','Communicating clearly and concisely','Speaking confidently with senior colleagues','Assertiveness','Expressing disagreement respectfully','Having difficult conversations','Setting boundaries and saying no','Handling defensiveness','Avoiding over-explanation'];document.getElementById('adminView').innerHTML=`<h2>Mid-course assessment</h2><div class="wrv-answer-grid">${answer('Assessment status',s.assessmentComplete?'Completed':'Not completed')}${s.midScores?dims.map((d,i)=>answer(d,`${s.midScores[i]??'—'}/10`)).join(''):''}${answer('Where has the client noticed the greatest improvement?',a.greatestImprovement)}${answer('Evidence of handling a situation differently',a.evidenceSituation)}${answer('Leadership situation that still feels uncomfortable',a.remainingChallenge)}</div>`}
function render(){stats();if(!data){document.getElementById('adminView').innerHTML='<div class="wrv-admin-empty">No client data has been synced yet.</div>';return}({overview,responses,daily,assessment}[section]||overview)()}
async function load(){const r=await fetch('/api/session',{cache:'no-store'});const s=await r.json();if(!s.authenticated||s.role!=='admin'){location.href='/?admin=1';return}document.getElementById('adminStatus').textContent='Administrator';const d=await fetch('/api/data',{cache:'no-store'});const out=await d.json();if(d.ok)data=out.data;render()}
document.querySelectorAll('.wrv-admin-sidebar [data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.wrv-admin-sidebar [data-section]').forEach(x=>x.classList.remove('active'));b.classList.add('active');section=b.dataset.section;render()});document.getElementById('adminLogout').onclick=async()=>{await fetch('/api/logout',{method:'POST'});location.href='/?admin=1'};load();setInterval(async()=>{try{const r=await fetch('/api/data',{cache:'no-store'});if(r.ok){data=(await r.json()).data;render()}}catch{}},30000);
})();
