(()=>{
const qs=new URLSearchParams(location.search);
let role=qs.get('admin')==='1'?'admin':'client';
let lastSnapshot='';
let syncing=false;
let cloudAvailable=true;
const $=(s,r=document)=>r.querySelector(s);
function overlay(){
 const el=document.createElement('div');el.className='wrv-auth-overlay';el.innerHTML=`<section class="wrv-auth-visual"><div class="wrv-auth-brand"><div class="wrv-auth-logo">Work Ready Vault</div><small>Executive Leadership Coaching · A division of Foundations Counselling Academy</small></div><div class="wrv-auth-copy"><span class="kicker">Reflect · Grow · Lead</span><h1>Build the leader your next chapter requires.</h1><p>A private coaching space for deliberate practice, reflection, communication growth and measurable leadership development.</p></div></section><section class="wrv-auth-panel"><form class="wrv-auth-card" id="wrvLogin"><h2>Welcome back</h2><p>Sign in to continue your Executive Leadership Readiness Programme.</p><div class="wrv-role-toggle"><button type="button" data-role="client">Client</button><button type="button" data-role="admin">Administrator</button></div><label class="wrv-auth-field"><span>Access code</span><input type="password" name="password" autocomplete="current-password" required placeholder="Enter your private access code"></label><button class="wrv-auth-submit" type="submit">Sign in securely →</button><p class="wrv-auth-error" id="wrvAuthError"></p><p class="wrv-auth-foot">Work Ready Vault · A division of Foundations Counselling Academy</p></form></section>`;document.body.prepend(el);
 const paint=()=>{el.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role===role))};paint();
 el.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;paint()});
 $('#wrvLogin',el).onsubmit=async e=>{e.preventDefault();const error=$('#wrvAuthError',el);error.textContent='';const btn=$('.wrv-auth-submit',el);btn.disabled=true;btn.textContent='Signing in…';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,password:e.target.password.value})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to sign in');if(data.role==='admin'){location.href='/admin.html';return}await activateClient(el)}catch(err){error.textContent=err.message}finally{btn.disabled=false;btn.textContent='Sign in securely →'}};
 return el;
}
function readLocal(){let a={},b={};try{a=JSON.parse(localStorage.getItem('elrpState')||'{}')}catch{}try{b=JSON.parse(localStorage.getItem('elrpDailyHabits')||'{}')}catch{}return{elrpState:a,elrpDailyHabits:b}}
function snapshot(){return JSON.stringify(readLocal())}
function isEmptyPayload(payload){return !Object.keys(payload.elrpState||{}).length&&!Object.keys(payload.elrpDailyHabits||{}).length}
async function push(force=false){if(syncing||!cloudAvailable)return;const current=snapshot();if(!force&&current===lastSnapshot)return;syncing=true;markSync('Syncing…');try{const payload=JSON.parse(current);const r=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let out={};try{out=await r.json()}catch{}if(r.ok&&out.cloudAvailable===false){cloudAvailable=false;lastSnapshot=current;markSync('Local only')}else if(r.ok){lastSnapshot=current;markSync('Synced')}else if(r.status===503||String(out.error||'').includes('BLOB_READ_WRITE_TOKEN')){cloudAvailable=false;console.warn('WRV cloud storage unavailable; continuing with local browser storage.');markSync('Local only')}else{console.error('WRV sync failed',r.status,out);markSync('Sync error')}}catch(err){console.error('WRV sync failed',err);markSync('Sync error')}finally{syncing=false}}
function markSync(text){const host=document.querySelector('.user-chip');if(!host)return;let chip=host.querySelector('.wrv-sync-chip');if(!chip){chip=document.createElement('span');chip.className='wrv-sync-chip';host.appendChild(chip)}chip.textContent=`● ${text}`}
function addLogout(){const host=document.querySelector('.user-chip');if(!host||host.querySelector('.wrv-logout'))return;const b=document.createElement('button');b.className='wrv-logout';b.textContent='Sign out';b.onclick=async()=>{await push(true);await fetch('/api/logout',{method:'POST'});location.href='/'};host.appendChild(b)}
async function activateClient(el){
 try{const r=await fetch('/api/data',{cache:'no-store'});const out=await r.json();if(r.ok&&out.cloudAvailable===false){cloudAvailable=false;markSync('Local only')}else if(!r.ok){if(r.status===503||String(out.error||'').includes('BLOB_READ_WRITE_TOKEN')){cloudAvailable=false;markSync('Local only')}else throw new Error(out.error||'Unable to load cloud data')}if(r.ok&&out.cloudAvailable!==false&&out.data){const server=out.data;const local=readLocal();const serverPayload={elrpState:server.elrpState||{},elrpDailyHabits:server.elrpDailyHabits||{}};const serverSnap=JSON.stringify(serverPayload);const localSnap=JSON.stringify(local);if(serverSnap!==localSnap&&!qs.has('cloud')){localStorage.setItem('elrpState',JSON.stringify(serverPayload.elrpState));localStorage.setItem('elrpDailyHabits',JSON.stringify(serverPayload.elrpDailyHabits));const u=new URL(location.href);u.searchParams.set('cloud','1');location.replace(u.toString());return}lastSnapshot=serverSnap}else{const local=readLocal();if(isEmptyPayload(local))lastSnapshot=JSON.stringify(local);else await push(true)}}
 catch(err){console.error('WRV cloud load failed',err);markSync('Sync error')}
 el.remove();setTimeout(()=>{if(!document.querySelector('.wrv-sync-chip'))markSync(cloudAvailable?'Synced':'Local only');addLogout()},100);setInterval(()=>{if(cloudAvailable)push(false)},5000);document.addEventListener('visibilitychange',()=>{if(cloudAvailable&&document.visibilityState==='hidden')push(true)});window.addEventListener('beforeunload',()=>{if(!cloudAvailable)return;const payload=snapshot();try{navigator.sendBeacon('/api/data',new Blob([payload],{type:'application/json'}))}catch{push(true)}})
}
async function boot(){const gate=overlay();try{const r=await fetch('/api/session',{cache:'no-store'});const s=await r.json();if(s.authenticated){if(s.role==='admin'){location.href='/admin.html';return}await activateClient(gate)}}catch{}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
