(()=>{
const content={
week1:{theme:'Leadership Identity & Confidence',days:[
{focus:'Self-esteem',title:'Lead before the title',read:'Healthy leadership self-esteem is the ability to recognise your value without needing constant external reassurance. Leadership begins with how you interpret responsibility, not with a job title. Each time you take ownership and create clarity for others, you strengthen the belief that you have something worthwhile to contribute.',task:'Choose one moment today to contribute an idea, decision or observation without first minimising it or apologising for it.',prompt:'What did I notice about my value and capability when I allowed myself to contribute fully?'},
{focus:'Confidence',title:'Build evidence, not hype',read:'Confidence grows when your mind can point to real evidence of capability. Instead of asking whether you feel confident enough, notice the decisions, conversations and problems you have already handled well. Confidence becomes more stable when it is based on evidence rather than mood.',task:'Write down one piece of evidence from your career that proves you can lead through challenge, then use that evidence before one important task today.',prompt:'What does this evidence remind me about my capability?'},
{focus:'Self-esteem',title:'Separate worth from performance',read:'A difficult meeting, mistake or disagreement can challenge performance without reducing personal worth. Strong leaders learn from outcomes without turning every setback into a judgement about themselves.',task:'When something feels uncomfortable today, describe the event factually and avoid using it as evidence that you are not good enough.',prompt:'How did separating my worth from the outcome change my response?'},
{focus:'Communication',title:'Make your leadership visible',read:'People cannot experience leadership qualities that remain only in your intentions. Clear communication makes values visible through words, tone, listening and follow-through.',task:'Choose one leadership quality and communicate it deliberately today through one conversation, email or meeting contribution.',prompt:'What did I communicate, and how did I make my leadership intention visible?'},
{focus:'Confidence',title:'Trust your judgement',read:'Strong judgement does not mean always being right. It means gathering enough information, making a reasoned decision and being willing to adjust when new information appears.',task:'Make one appropriate decision today without unnecessary over-checking, seeking repeated reassurance or over-explaining.',prompt:'What helped me trust my judgement more today?'}]},
week2:{theme:'Executive Presence & Personal Authority',days:[
{focus:'Presentation skills',title:'Presence starts before speaking',read:'Presentation begins before the first sentence. Pace, posture, eye contact, breathing and how comfortably you occupy silence all affect how your message is received. The goal is not performance for its own sake; it is to help your audience experience you as grounded and clear.',task:'Before one important interaction, settle your breathing, posture and pace for 30 seconds, then begin more slowly than usual.',prompt:'What changed in my delivery when I entered the interaction more deliberately?'},
{focus:'Confidence',title:'Pause is authority',read:'A pause can communicate thoughtfulness and control. Rushing to fill silence may make a strong idea sound less considered than it actually is. Confidence often looks like giving yourself permission to think before speaking.',task:'Pause for two seconds before answering one important question today.',prompt:'How did the pause affect my confidence and the quality of my response?'},
{focus:'Communication',title:'Lead with the point',read:'Senior communication is easier to follow when the main message comes first. State your position, then give the reason, the evidence and the next step. This structure reduces over-explaining and makes your contribution easier to remember.',task:'Use Position → Reason → Evidence → Next Step in one email, meeting contribution or conversation.',prompt:'Was my message clearer, shorter and easier to follow than usual?'},
{focus:'Self-esteem',title:'Stop auditioning',read:'Presence weakens when attention shifts from contribution to self-protection. When you focus excessively on how you are being judged, you may over-explain, rush or dilute your point. Your role is not to prove your worth in every interaction; it is to make a useful contribution.',task:'In one interaction, replace “How am I being judged?” with “What useful contribution is needed here?”',prompt:'What became easier when I focused on contribution instead of approval?'},
{focus:'Presentation skills',title:'Deliver with structure and calm',read:'A strong presentation is not defined by perfect words. It is defined by a clear opening, a logical message, controlled pace and a confident close. Structure gives both the speaker and the audience something to rely on.',task:'Give a 60–90 second spoken update today using: Context → Key Point → Evidence → Recommendation. Record it privately if there is no live opportunity.',prompt:'What was strongest in my delivery, and what one presentation habit will I improve next time?'}]},
week3:{theme:'Assertiveness & Difficult Conversations',days:[
{focus:'Communication',title:'Name the real issue',read:'Difficult conversations become harder when the issue remains vague. Clarity starts by describing what happened without exaggeration, character judgement or unnecessary history.',task:'Write and, where appropriate, say one sentence that describes a current issue using observable facts only.',prompt:'What became clearer once I removed judgement from the description?'},
{focus:'Assertiveness',title:'Listen without surrendering your position',read:'Assertiveness includes listening. Understanding another person’s perspective does not require agreeing with it. You can remain open, respectful and curious without abandoning your own view.',task:'In one disagreement, ask one genuine question before explaining your own position, then state your view without apologising for having it.',prompt:'What did I learn, and how well did I hold my own position?'},
{focus:'Assertiveness',title:'Say what you need',read:'People cannot reliably respond to expectations that remain implied. A respectful request is clearer than hoping another person will infer what you need. Assertiveness is specific, calm and direct.',task:'Make one clear request today, including the action, standard or outcome you need.',prompt:'Was I specific enough for the other person to know what success looks like?'},
{focus:'Presentation skills',title:'Speak under pressure',read:'Presentation skill is most valuable when the stakes rise. Under pressure, return to structure: one key message, two or three supporting points and a clear close. You do not need to say everything to sound credible.',task:'Rehearse a 90-second response to a challenging leadership question. Start with your answer, support it briefly, then stop.',prompt:'Where did I sound most credible, and where did I begin to over-explain or lose structure?'},
{focus:'Assertiveness',title:'Close the loop',read:'A difficult conversation is incomplete without clarity about what happens next. Agreement, ownership and follow-up turn a conversation into leadership action. Assertiveness includes ensuring that expectations do not disappear once the conversation ends.',task:'For one issue, confirm the agreed action, owner, standard and follow-up point.',prompt:'What changed when the conversation ended with a clear next step?'}]}}
;
function state(){try{return JSON.parse(localStorage.getItem('elrpDailyHabits')||'{}')}catch{return {}}}
function save(v){localStorage.setItem('elrpDailyHabits',JSON.stringify(v))}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]))}
function renderWeek(key){
 const root=document.getElementById(key); if(!root||root.querySelector('.daily-habit-section'))return;
 const challenge=root.querySelector('.challenge'); if(!challenge)return;
 const cfg=content[key]; if(!cfg)return; const st=state(); st[key]=st[key]||{};
 const section=document.createElement('article'); section.className='card step-card daily-habit-section';
 const complete=cfg.days.filter((_,i)=>st[key][i]?.done).length;
 section.innerHTML=`<div class="daily-habit-hero"><div><span class="daily-kicker">Daily Leadership Practice</span><h2>Read. Practise. Reflect.</h2><p>Five short daily repetitions built around your priority development areas: self-esteem, confidence, assertiveness, communication and presentation skills.</p></div><div class="daily-score"><strong>${complete}/5</strong><span>days complete</span></div></div><div class="daily-day-tabs">${cfg.days.map((d,i)=>`<button type="button" class="daily-tab ${i===0?'active':''} ${st[key][i]?.done?'done':''}" data-day="${i}"><span>Day ${i+1}</span><strong>${esc(d.title)}</strong><em>${esc(d.focus)}</em></button>`).join('')}</div><div class="daily-stage"></div>`;
 challenge.parentNode.insertBefore(section,challenge);
 let active=0; const stage=section.querySelector('.daily-stage'); const tabs=[...section.querySelectorAll('.daily-tab')];
 function render(){const d=cfg.days[active],entry=st[key][active]||{}; stage.innerHTML=`<div class="daily-focus-badge">Priority focus · ${esc(d.focus)}</div><div class="daily-reading"><div class="daily-reading-mark">READ</div><h3>${esc(d.title)}</h3><p>${esc(d.read)}</p></div><div class="daily-practice-box"><span>Today’s leadership practice</span><strong>${esc(d.task)}</strong></div><label class="daily-journal"><span>End-of-day reflection</span><strong>${esc(d.prompt)}</strong><textarea placeholder="Capture what happened, what you noticed and what you want to repeat...">${esc(entry.note||'')}</textarea></label><div class="daily-actions"><span class="daily-save">Saved in this browser</span><button type="button" class="daily-complete ${entry.done?'done':''}">${entry.done?'✓ Day complete':'Mark today complete'}</button></div>`;
 tabs.forEach((t,i)=>t.classList.toggle('active',i===active));
 stage.querySelector('textarea').addEventListener('input',e=>{st[key][active]=st[key][active]||{};st[key][active].note=e.target.value;save(st)});
 stage.querySelector('.daily-complete').addEventListener('click',()=>{st[key][active]=st[key][active]||{};st[key][active].done=!st[key][active].done;save(st);tabs[active].classList.toggle('done',st[key][active].done);const c=cfg.days.filter((_,i)=>st[key][i]?.done).length;section.querySelector('.daily-score strong').textContent=`${c}/5`;render()});
 }
 tabs.forEach((t,i)=>t.addEventListener('click',()=>{active=i;render()})); render();
}
function enhance(){['week1','week2','week3'].forEach(renderWeek)}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,60)}).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();