(()=>{
const content={
week1:{theme:'Leadership Identity & Confidence',days:[
{title:'Lead before the title',read:'Leadership begins with how you interpret responsibility, not with a job title. Each time you take ownership, make a thoughtful decision or create clarity for others, you are practising leadership identity.',task:'Choose one moment today to act from responsibility rather than waiting for permission.',prompt:'Where did I act like the leader I want to become today?'},
{title:'Build evidence, not hype',read:'Confidence grows when your mind can point to real evidence of capability. Instead of asking whether you feel confident enough, notice the decisions, conversations and problems you have already handled well.',task:'Write down one piece of evidence from your career that proves you can lead through challenge.',prompt:'What does this evidence remind me about my capability?'},
{title:'Notice hesitation',read:'Hesitation is useful information. It often shows where you fear judgement, conflict, uncertainty or getting something wrong. The goal is not to eliminate hesitation, but to recognise it early enough to choose your response.',task:'Catch one moment of second-guessing and ask: “What does this situation need from me as a leader?”',prompt:'What triggered the hesitation, and what did I choose to do?'},
{title:'Define your leadership signature',read:'People experience leadership through repeated behaviour. Calmness, clarity, fairness, courage and consistency become credible only when they can be seen in action.',task:'Choose one quality from your Leadership Compass and demonstrate it deliberately today.',prompt:'How did I make that quality visible in my behaviour?'},
{title:'Trust your judgement',read:'Strong judgement does not mean always being right. It means gathering enough information, making a reasoned decision and being willing to adjust when new information appears.',task:'Make one appropriate decision today without unnecessary over-checking or over-explaining.',prompt:'What helped me trust my judgement more today?'}]},
week2:{theme:'Executive Presence & Personal Authority',days:[
{title:'Presence starts before speaking',read:'Executive presence is often communicated before the first sentence. Pace, posture, attention, facial expression and how comfortably you occupy silence all signal whether you feel grounded.',task:'Before one important interaction, settle your breathing, posture and pace for 30 seconds.',prompt:'What changed when I entered the interaction more deliberately?'},
{title:'Pause is authority',read:'A pause can communicate thoughtfulness and control. Rushing to fill silence may make a strong idea sound less considered than it actually is.',task:'Pause for two seconds before answering one important question today.',prompt:'How did the pause affect my response and the room?'},
{title:'Lead with the point',read:'Senior communication is easier to follow when the main message comes first. State your position, then give the reason, the evidence and the next step.',task:'Use Position → Reason → Evidence → Next Step in one email, meeting contribution or conversation.',prompt:'Was my message clearer and shorter than usual?'},
{title:'Stop auditioning',read:'Presence weakens when attention shifts from contribution to self-protection. When you focus excessively on how you are being judged, you may over-explain, rush or dilute your point.',task:'In one interaction, replace “How am I being judged?” with “What useful contribution is needed here?”',prompt:'What became easier when I focused on contribution?'},
{title:'Hold your position calmly',read:'Personal authority is not aggression. It is the ability to state a considered view, stay open to challenge and remain composed without immediately retreating.',task:'State one recommendation clearly and allow space for others to respond before adding more explanation.',prompt:'How did it feel to let my recommendation stand on its own?'}]},
week3:{theme:'Assertiveness & Difficult Conversations',days:[
{title:'Name the real issue',read:'Difficult conversations become harder when the issue remains vague. Clarity starts by describing what happened without exaggeration, character judgement or unnecessary history.',task:'Write one sentence that describes a current issue using observable facts only.',prompt:'What became clearer once I removed judgement from the description?'},
{title:'Listen without surrendering your position',read:'Assertiveness includes listening. Understanding another person’s perspective does not require agreeing with it, and listening well often lowers defensiveness enough for the real issue to be discussed.',task:'In one disagreement, ask one genuine question before explaining your own position.',prompt:'What did I learn that I would have missed if I had responded immediately?'},
{title:'Say what you need',read:'People cannot reliably respond to expectations that remain implied. A respectful request is clearer than hoping another person will infer what you need.',task:'Make one clear request today, including the action or outcome you need.',prompt:'Was I specific enough for the other person to know what success looks like?'},
{title:'Practise respectful disagreement',read:'Disagreement is not automatically conflict. Mature leadership makes room for different views while protecting respect, clarity and the working relationship.',task:'Use the sentence: “I see it differently. My concern is…” in an appropriate conversation or rehearse it for a real situation.',prompt:'What helps me disagree without becoming apologetic or defensive?'},
{title:'Close the loop',read:'A difficult conversation is incomplete without clarity about what happens next. Agreement, ownership and follow-up turn a conversation into leadership action.',task:'For one issue, confirm the agreed action, owner and follow-up point.',prompt:'What changed when the conversation ended with a clear next step?'}]}}
;
function state(){try{return JSON.parse(localStorage.getItem('elrpDailyHabits')||'{}')}catch{return {}}}
function save(v){localStorage.setItem('elrpDailyHabits',JSON.stringify(v))}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderWeek(key){
 const root=document.getElementById(key); if(!root||root.querySelector('.daily-habit-section'))return;
 const challenge=root.querySelector('.challenge'); if(!challenge)return;
 const cfg=content[key]; if(!cfg)return; const st=state(); st[key]=st[key]||{};
 const section=document.createElement('article'); section.className='card step-card daily-habit-section';
 const complete=cfg.days.filter((_,i)=>st[key][i]?.done).length;
 section.innerHTML=`<div class="daily-habit-hero"><div><span class="daily-kicker">Daily Leadership Practice</span><h2>Read. Practise. Reflect.</h2><p>Five short daily repetitions to turn this week’s learning into visible leadership habits.</p></div><div class="daily-score"><strong>${complete}/5</strong><span>days complete</span></div></div><div class="daily-day-tabs">${cfg.days.map((d,i)=>`<button type="button" class="daily-tab ${i===0?'active':''} ${st[key][i]?.done?'done':''}" data-day="${i}"><span>Day ${i+1}</span><strong>${esc(d.title)}</strong></button>`).join('')}</div><div class="daily-stage"></div>`;
 challenge.parentNode.insertBefore(section,challenge);
 let active=0; const stage=section.querySelector('.daily-stage'); const tabs=[...section.querySelectorAll('.daily-tab')];
 function render(){const d=cfg.days[active],entry=st[key][active]||{}; stage.innerHTML=`<div class="daily-reading"><div class="daily-reading-mark">READ</div><h3>${esc(d.title)}</h3><p>${esc(d.read)}</p></div><div class="daily-practice-box"><span>Today’s leadership practice</span><strong>${esc(d.task)}</strong></div><label class="daily-journal"><span>End-of-day reflection</span><strong>${esc(d.prompt)}</strong><textarea placeholder="Capture what happened, what you noticed and what you want to repeat...">${esc(entry.note||'')}</textarea></label><div class="daily-actions"><span class="daily-save">Saved in this browser</span><button type="button" class="daily-complete ${entry.done?'done':''}">${entry.done?'✓ Day complete':'Mark today complete'}</button></div>`;
 tabs.forEach((t,i)=>t.classList.toggle('active',i===active));
 stage.querySelector('textarea').addEventListener('input',e=>{st[key][active]=st[key][active]||{};st[key][active].note=e.target.value;save(st)});
 stage.querySelector('.daily-complete').addEventListener('click',()=>{st[key][active]=st[key][active]||{};st[key][active].done=!st[key][active].done;save(st);tabs[active].classList.toggle('done',st[key][active].done);const c=cfg.days.filter((_,i)=>st[key][i]?.done).length;section.querySelector('.daily-score strong').textContent=`${c}/5`;render()});
 }
 tabs.forEach((t,i)=>t.addEventListener('click',()=>{active=i;render()})); render();
}
function enhance(){['week1','week2','week3'].forEach(renderWeek)}
let timer;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(enhance,60)}).observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();